my_project/application/views.py
from flask import render_template, redirect, url_for, Blueprint, flash,request,abort
from flask_login import login_user, logout_user, login_required,current_user
from my_project import db   
from my_project.models import User,TicketApplication
from my_project.application.forms import ApplicationForTicketForm 

apply_tickets=Blueprint('apply_tickets',__name__)

@apply_tickets.route('/apply',methods=['GET','POST'])
@login_required
def apply():
    if current_user.tickets_application: # if current user have application
        abort(400)

    form=ApplicationForTicketForm()

    if form.validate_on_submit():

        apply=TicketApplication(name=form.name.data,
                                surname=form.surname.data,
                                date_of_birth=form.date_of_birth.data,
                                country=form.country.data,
                                city=form.city.data,
                                address=form.address.data,
                                email=form.email.data,
                                number_of_tickets=form.number_of_tickets.data,
                                user_id=current_user.id)
        db.session.add(apply)
        db.session.commit()
        flash('Your application for tickets was succesfull')
        return redirect(url_for('core.index'))
    return render_template('apply.html',form=form)

@apply_tickets.route('/apply_check')
@login_required
def apply_check():
    if current_user.tickets_application: # ako logirani user ima napravljenu aplikaciju za karte
        your_application = TicketApplication.query.get_or_404(current_user.tickets_application.id)
    else:
        abort(406)

    return render_template('apply_check.html',your_application=your_application)

@apply_tickets.route('/update/<int:application_id>',methods=['GET','POST'])
@login_required
def update(application_id):
    
    your_application=TicketApplication.query.get_or_404(application_id)

    form=ApplicationForTicketForm()

    if form.validate_on_submit():
        your_application.name=form.name.data
        your_application.surname=form.surname.data
        your_application.date_of_birth=form.date_of_birth.data
        your_application.country=form.country.data
        your_application.city=form.city.data
        your_application.address=form.address.data
        your_application.email=form.email.data
        your_application.number_of_tickets=form.number_of_tickets.data            

        db.session.commit()
        flash('Application updated')
        return redirect (url_for('apply_tickets.apply_check'))
        
    elif request.method=='GET':
        form.name.data=your_application.name
        form.surname.data=your_application.surname
        form.date_of_birth.data=your_application.date_of_birth
        form.country.data=your_application.country
        form.city.data=your_application.city
        form.address.data=your_application.address
        form.email.data=your_application.email
        form.number_of_tickets.data=your_application.number_of_tickets
        
    return render_template('apply.html',form=form)       
    
@apply_tickets.route('/delete/<int:application_id>',methods=['GET','POST'])
@login_required
def delete(application_id):
    your_application=TicketApplication.query.get_or_404(application_id)
    db.session.delete(your_application)
    db.session.commit()

    return redirect (url_for('core.index'))

my_project/core/views.py
from flask import render_template, redirect,url_for, Blueprint
from my_project import db   
from my_project.models import User,TicketApplication,Winners
import random
from datetime import datetime
from my_project.core.email_handler import send_winner_notification_email


core=Blueprint('core',__name__)


@core.route('/')
def index():

    all_applications=TicketApplication.query.all()
    number_of_applications=len(all_applications)

    return render_template('index.html',number_of_applications=number_of_applications)


@core.route('/winners')
def winners():
    specific_datetime = datetime(year=2023, month=12, day=23, hour=12, minute=50, second=0)      
    current_datetime = datetime.now()
    all_applications=TicketApplication.query.all()
    number_of_applications=len(all_applications)

    if current_datetime>specific_datetime:

        winners=Winners.query.all()
        if len(winners)==0: # ne mogu koristit is None jer ce ovaj query vratit praznu list sta znaci da None nece bit nikada zato stavljan if duljina liste nije 0 
            if len(all_applications) >= 2: # ako se prijavilo dvoje ili vise
                winning_applications = random.sample(all_applications, k=2) # onda izaberi raandom dvoje
            else: # ako se nije dvoje znaci da je jedan ili niko
                winning_applications = all_applications # ako je niko ova doli for petlja se nece moc izvrsit a ako je jedno onda ce se moc     
            
            for winning_application in winning_applications:
                winner=Winners(application_id=winning_application.id)
                db.session.add(winner)
                send_winner_notification_email(winning_application.email)

            db.session.commit()      

        return render_template('winners.html',winners=winners,number_of_applications=number_of_applications)
    else:        
        return render_template('not_yet.html',number_of_applications=number_of_applications,specific_datetime=specific_datetime)

my_project/users/views.py
from flask import render_template, redirect, url_for, Blueprint, flash,request
from flask_login import login_user, logout_user, login_required,current_user
from my_project import db   
from my_project.models import User
from my_project.users.forms import RegistrationForm, LoginForm

users=Blueprint('users',__name__)

@users.route('/register',methods=['GET','POST'])
def register():

    form=RegistrationForm()

    if form.validate_on_submit():
        user=User(email=form.email.data,username=form.username.data,password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User registered successfully')
        return redirect(url_for('users.login'))
    
    return render_template('register.html',form=form)

@users.route('/login',methods=['GET','POST'])
def login():

    form=LoginForm()

    if form.validate_on_submit():

        user=User.query.filter_by(email=form.email.data).first()
        
        if user is not None and user.check_password(password=form.password.data):
            login_user(user)
            flash('User logged in successfully')

            next=request.args.get('next')

            if next==None or not next[0]=='/':
                next=url_for('core.index')
            
            return redirect(next)
    return render_template('login.html',form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('User logged out sucessfully')
    return redirect(url_for('core.index'))

my_project/templates/apply.html
{% extends 'base.html' %}{% block content %}
<form method="POST">
  {{form.hidden_tag()}} <br />
  <div class="form-group">
    {{form.name.label(class="form-group")}}{{form.name(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.surname.label(class="form-group")}}{{form.surname(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.date_of_birth.label(class="form-group")}}{{form.date_of_birth(class='form-control')}}
    {% for error in form.date_of_birth.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
        class="fade close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
      {{error}}
    </div>
    {% endfor %}
  </div>
  <div class="form-group">
    {{form.country.label(class="form-group")}}{{form.country(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.city.label(class="form-group")}}{{form.city(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.address.label(class="form-group")}}{{form.address(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.email.label(class="form-group")}}{{form.email(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.number_of_tickets.label(class="form-group")}}{{form.number_of_tickets(class='form-control')}}
    {% for error in form.number_of_tickets.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
        class="fade close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
      {{error}}
    </div>
    {% endfor %}
  </div>
  <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
</form>

{% endblock %}

my_project/templates/apply_check.html
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
  <p>Application ID: {{your_application.id}}</p>
  <p>Name: {{your_application.name}}</p>
  <p>Surname: {{your_application.surname}}</p>
  <p>Date of birth: {{your_application.date_of_birth.strftime('%d.%m.%Y')}}</p>
  <p>Country: {{your_application.country}}</p>
  <p>City: {{your_application.city}}</p>
  <p>Address: {{your_application.address}}</p>
  <p>Email: {{your_application.email}}</p>
  <p>Number of tickets: {{your_application.number_of_tickets}}</p>
  <div>
    <a
      href="{{url_for('apply_tickets.update',application_id=your_application.id)}}"
      >Update</a
    >
    <button
      type="button"
      class="btn btn-danger"
      data-toggle="modal"
      data-target="#del_modal"
    >
      Delete
    </button>
  </div>
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Application?</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete your application?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Cancel
          </button>

          <form
            action="{{url_for('apply_tickets.delete',application_id=your_application.id)}}"
            method="post"
          >
            <input class="btn btn-danger" type="submit" value="Delete" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

my_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ticket Application</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{{ url_for('core.index') }}">Home</a>
        <a class="nav-item nav-link" href="{{ url_for('core.winners') }}"
          >Winners</a
        >
        {% if current_user.is_authenticated %}
        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}"
          >Logout</a
        >
        <a class="nav-item nav-link" href="{{ url_for('apply_tickets.apply') }}"
          >Apply for Tickets</a
        >
        <a
          class="nav-item nav-link"
          href="{{ url_for('apply_tickets.apply_check') }}"
          >View Application</a
        >
        {% else %}
        <a class="nav-item nav-link" href="{{ url_for('users.login') }}"
          >Login</a
        >
        <a class="nav-item nav-link" href="{{ url_for('users.register') }}"
          >Register</a
        >

        {% endif %}
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
  </body>
</html>

my_project/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
  {% if current_user.is_authenticated %}
  <h1>Welcome {{current_user.username}}</h1>
  {% endif %}
  <h1>Welcome to EURO tickets application page</h1>
  <p>
    Please register, login to site and apply for tickets. You can apply only up
    to 4 tickets.
  </p>
  <p>There can be only two winners.</p>
  <p>
    After some time id of winning applicants will be posted and notified on
    their email.
  </p>
  <p>Number of current applications is: {{number_of_applications}}</p>
</div>
{% endblock %}

my_project/templates/login.html
{% extends 'base.html' %}{% block content %}
<form method="POST">
  {{form.hidden_tag()}}
  <div class="form-group">
    {{form.email.label(class="form-group")}}{{form.email(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.password.label(class="form-group")}}{{form.password(class='form-control')}}
  </div>

  <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
</form>

{% endblock %}

my_project/templates/not_yet.html
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
  <h3>Current number of applications is: {{number_of_applications}}</h3>
  <h1>
    Winners will be visible after: {{specific_datetime.strftime('%d.%m.%Y')}}
  </h1>
  {% endblock %}
</div>

my_project/templates/register.html
{% extends 'base.html' %}{% block content %}
<form method="POST">
  {{form.hidden_tag()}} <br />
  <div class="form-group">
    {{form.email.label(class="form-group")}}{{form.email(class='form-control')}}
  </div>
  {% for error in form.email.errors %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button
      type="button"
      class="close"
      data-dismiss="alert"
      aria-label="Close"
      class="fade close"
    >
      <span aria-hidden="true">&times;</span>
    </button>
    {{error}}
  </div>
  {% endfor %}
  <div class="form-group">
    {{form.username.label(class="form-group")}}{{form.username(class='form-control')}}
  </div>
  {% for error in form.username.errors %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button
      type="button"
      class="close"
      data-dismiss="alert"
      aria-label="Close"
      class="fade close"
    >
      <span aria-hidden="true">&times;</span>
    </button>
    {{error}}
  </div>
  {% endfor %}
  <div class="form-group">
    {{form.password.label(class="form-group")}}{{form.password(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.pass_confirm.label(class="form-group")}}{{form.pass_confirm(class='form-control')}}
  </div>
  <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
</form>

{% endblock %}

my_project/templates/winners.html
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
  {% if not number_of_applications %}
  <!-- ako je broj aplikacija 0 onda je false -->
  <h1>Nobody applied for wining the tickets</h1>
  {% else %}
  <h1>Winners are applicants with theese application IDs:</h1>
  <ul>
    {% for winner in winners %}
    <li>Application ID:{{winner.tick_application.id}}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>
{% endblock %}